"""delete

Revision ID: 010a70d3109e
Revises: db2ff80724a1
Create Date: 2023-09-15 11:52:29.027249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010a70d3109e'
down_revision = 'db2ff80724a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crimes', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_crimes_location_id_locations'), 'locations', ['location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crimes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_crimes_location_id_locations'), type_='foreignkey')
        batch_op.alter_column('location_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
