"""map

Revision ID: b0ad46a865fa
Revises: 
Create Date: 2023-10-05 11:13:54.201622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ad46a865fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crime_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crime_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['crime_id'], ['crimes.id'], name=op.f('fk_crime_categories_crime_id_crimes')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crime_location_association',
    sa.Column('crime_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crime_id'], ['crimes.id'], name=op.f('fk_crime_location_association_crime_id_crimes')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_crime_location_association_location_id_locations'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_users_location_id_locations')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('crime_location_association')
    op.drop_table('crime_categories')
    op.drop_table('locations')
    op.drop_table('crimes')
    # ### end Alembic commands ###
