"""delete

Revision ID: db2ff80724a1
Revises: aa0c7a7bdf3b
Create Date: 2023-09-15 11:49:17.143308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2ff80724a1'
down_revision = 'aa0c7a7bdf3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_locations_crime_id_crimes', type_='foreignkey')
        batch_op.drop_column('crime_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crime_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_locations_crime_id_crimes', 'crimes', ['crime_id'], ['id'])

    # ### end Alembic commands ###
